import { useEffect, useState } from "react";
import { Redirect, type Href } from "expo-router";

import { getAccessToken } from "@/lib/supabase";
import { DEMO_STORY, isRenderableDemoStory } from "@/lib/demo-story";
import { resolveFirstOpenStartup } from "@/lib/auth-startup";
import type { FirstOpenRoute } from "@/lib/first-open";
import { hasSeenDemo } from "@/lib/first-open-state";

/**
 * Issue 174 — first-open gate. The routing decision itself is the pure
 * `resolveFirstOpenRoute` (tested in tests/174-first-open-demo-entry.test.ts);
 * this component only gathers its inputs. While resolving we render nothing —
 * the splash screen is still up, so there is no flash (PERF-4).
 */
export default function Index() {
  const [route, setRoute] = useState<FirstOpenRoute | null>(null);

  useEffect(() => {
    let alive = true;
    resolveFirstOpenStartup({
      getSession: async () => {
        try {
          return (await getAccessToken()) !== null;
        } catch {
          // Auth storage unavailable → treat as signed out; funnel still works.
          return false;
        }
      },
      hasSeenDemo,
      demoRenderable: isRenderableDemoStory(DEMO_STORY),
    }).then((nextRoute) => {
      if (alive) setRoute(nextRoute);
    });
    return () => {
      alive = false;
    };
  }, []);

  if (!route) return null;
  // Cast: .expo/types typed routes are only regenerated by `expo start`, so a
  // freshly added screen ("/demo") isn't in the union yet at typecheck time.
  return <Redirect href={route as Href} />;
}
